# Binomial Distributions
Use NumPy to create simulations and compute proportions for the following outcomes. The first one is done for you.

In [1]:
# import numpy
import numpy as np

### 1. A fair coin flip produces heads

In [133]:
# simulate 1 million tests of one fair coin flip
# remember, the output of these tests are the # successes, or # heads
tests = np.random.binomial(1, 0.5, int(1e6))
tests

array([1, 0, 0, ..., 0, 0, 0])

In [134]:
# proportion of tests that produced heads
(tests == 1).mean()

0.49958999999999998

### 2. Five fair coin flips produce exactly one head

In [152]:
# simulate 1 million tests of five fair coin flips
tests = np.random.binomial(5, 0.5, int(1e6))
tests

array([2, 3, 3, ..., 2, 1, 1])

In [153]:
# proportion of tests that produced 1 head
(tests == 1).mean()

0.15665000000000001

### 3. Ten fair coin flips produce exactly four heads

In [149]:
# simulate 1 million tests of ten fair coin flips
tests = np.random.binomial(10, 0.5, int(1e6))
tests

array([4, 7, 6, ..., 7, 3, 3])

In [150]:
# proportion of tests that produced 4 heads
(tests == 4).mean()

0.20483299999999999

### 4. Five biased coin flips with P(H) = 0.8 produce exactly five heads

In [144]:
# simulate 1 million tests of five biased coin flips
tests = np.random.binomial(5, 0.8, int(1e6))
tests

array([3, 4, 4, ..., 3, 5, 5])

In [147]:
# proportion of tests that produced 5 heads
(tests == 5).mean()

0.327519

### 5. Ten biased coin flips with P(H) = 0.15 produce at least 3 heads

In [158]:
# simulate 1 million tests of ten biased coin flips
tests = np.random.binomial(10, 0.15, int(1e6))
tests

array([3, 1, 1, ..., 0, 2, 0])

In [161]:
# proportion of tests that produced at least 3 heads
(tests >= 3).mean()

0.18093300000000001